remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

title: [Waleed Ahmed]
description: [MACS Student]

github:
  zip_url: http://example.com/download.zip
  another_url: http://home.waleeday.com